stages:
  - build 
  - run

build:
  stage: build
  image: docker:24.0.7-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker compose build
    - docker compose run -d 
      
run:
  stage: run
  image: docker:24.0.7-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker compose build
    - docker compose run -d 