default:
  image : docker
  services:
    - docker
  before_script:
    - docker info

stages:
  - test-run

test-run:
  stage: test-run
  script:
    - echo "test"
  artifacts:
    paths:
      - test/*.jar
