default:
  image: docker
  services:
    - docker
  before_script:
    - docker info

test-run:
  stage: test-run
  script:
    - docker compose build
    - docker compose up
  artifacts:
    paths:
      - test/*.jar

