services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres:/data/postgres
      - ~/students/Database:/data/database
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres: