services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-def555}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ~/students/Database:/data/database
      - ~/students/Database/create_database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres: